# Generated by Django 5.1.2 on 2024-11-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('LeagueId', models.AutoField(primary_key=True, serialize=False)),
                ('LeagueName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamId', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=500)),
                ('League', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerId', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=500)),
                ('Team', models.CharField(max_length=500)),
                ('Positions', models.ManyToManyField(to='stats.position')),
            ],
        ),
    ]
