# Generated by Django 5.1.2 on 2024-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='League',
            field=models.PositiveIntegerField(),
        ),
    ]
