# Generated by Django 5.1.2 on 2024-11-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Team',
            field=models.PositiveIntegerField(),
        ),
    ]
