# Generated by Django 5.1.2 on 2024-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='PlayerName',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='player',
            name='LastName',
            field=models.CharField(default='not set', max_length=500),
        ),
    ]
