# Generated by Django 5.1.2 on 2024-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_rename_playername_player_firstname_player_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Bats',
            field=models.CharField(default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Throws',
            field=models.CharField(default='R', max_length=1),
            preserve_default=False,
        ),
    ]
