# Generated by Django 5.1.2 on 2024-11-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_player_bats_player_throws'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('PitchId', models.AutoField(primary_key=True, serialize=False)),
                ('GameId', models.PositiveIntegerField()),
                ('PitcherId', models.PositiveIntegerField()),
                ('BatterId', models.PositiveIntegerField()),
                ('PitchType', models.CharField(max_length=100)),
                ('PitchCall', models.CharField(max_length=100)),
                ('Swing', models.BooleanField(blank=True, default=False)),
                ('Contact', models.BooleanField(blank=True, default=False)),
                ('BallInPlay', models.BooleanField(blank=True, default=False)),
                ('BallInPlayType', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Bases', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('Rbi', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
