# Generated by Django 5.1.2 on 2024-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_pitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('VisitingTeamId', models.PositiveIntegerField()),
                ('HomeTeamId', models.PositiveIntegerField()),
                ('LeagueId', models.PositiveIntegerField()),
            ],
        ),
    ]
