# Generated by Django 5.1.2 on 2024-11-13 20:27

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_player_jerseynumber_alter_player_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('PlayId', models.AutoField(primary_key=True, serialize=False)),
                ('GameId', models.PositiveIntegerField()),
                ('BatterId', models.IntegerField()),
                ('PitcherId', models.IntegerField()),
                ('TotalBases', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('PlayType', models.CharField(max_length=100)),
                ('BallInPlayType', models.CharField(max_length=100)),
                ('OutsRecorded', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('Runs', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('EarnedRuns', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('PlayersScored', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('Errors', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='BallInPlay',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='Bases',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='Rbi',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='Swing',
        ),
        migrations.AddField(
            model_name='pitch',
            name='Outs',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='PitchLocation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['middle', 'middle'], size=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='PlayId',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='SwingType',
            field=models.CharField(blank=True, default=False),
        ),
    ]
