# Generated by Django 5.1.2 on 2024-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_play_remove_pitch_ballinplay_remove_pitch_bases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='PlayId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='SwingType',
            field=models.CharField(blank=True, default='take'),
        ),
    ]
