# Generated by Django 5.1.2 on 2024-11-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_pitch_playid_alter_pitch_swingtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='Errors',
        ),
    ]
