# Generated by Django 5.1.2 on 2024-11-15 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_alter_play_playersscored'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='FieldingSequence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
