# Generated by Django 5.1.2 on 2024-11-15 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_play_fielderonhit'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='BasesAdvancedFromFirst',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='play',
            name='BasesAdvancedFromSecond',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='play',
            name='BasesAdvancedFromThird',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
