# Generated by Django 5.1.2 on 2024-11-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_play_basesadvancedfromfirst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='BallInPlayType',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='Outs',
        ),
    ]
