# Generated by Django 5.1.2 on 2024-11-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_remove_pitch_ballinplaytype_remove_pitch_outs'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='abbrev',
            field=models.CharField(default='nl', max_length=100),
            preserve_default=False,
        ),
    ]
