# Generated by Django 5.1.2 on 2024-11-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_position_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbrev',
            field=models.CharField(max_length=2),
        ),
    ]
