# Generated by Django 5.1.2 on 2024-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_alter_player_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='HomeField',
            field=models.CharField(default='not set', max_length=500),
            preserve_default=False,
        ),
    ]
