# Generated by Django 5.1.2 on 2024-12-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_team_homefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
